---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/controlcomprobante.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_controlcomprobante/
      - /bin/rsync -av ./ $DEPLOYPATH

