---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolutionweli/public_html/controlcomprobante.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolutionweli/web_controlcomprobante/
      - /bin/rsync -av ./ $DEPLOYPATH

